version: "3"

services:
  db_2:
    image: mysql:5.7
    container_name: db_2
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sample_db_2
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3308:3308
    command: --port 3308
    tty: true

  api_2:
    depends_on:
      - db
    container_name: "api_2"
    build: ./sql_app
    ports:
      - "8000:8000"
    volumes:
      - ./sql_app:/usr/src/server